newIssueWelcomeComment: >
  Thank you for creating an issue! One of our team memebers will get back to you with additional information. 
  
  If this is a product issue, please close this and contact the particular product's support instead. For more information, see [Support for Microsoft products and apps](https://support.microsoft.com/all-products).
