name: "Bug Report 🐛"
description: Something is wrong with the docs.microsoft.com site.
labels: ["bug"]

body:
  - type: markdown
    attributes:
      value: "### Before you fill out and submit this issue"

  - type: markdown
    attributes:
      value: |
        - Please make sure to [search for existing issues](https://github.com/MicrosoftDocs/feedback/issues) and [check the Microsoft Docs Q&A](https://docs.microsoft.com/answers/products/)!
        - If this is a product issue, please contact the particular product's support instead of opening an issue here. For a list of support websites, see [Support for Microsoft products and apps](https://support.microsoft.com/all-products).

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of the bug.
    validations:
      required: true

  - type: textarea
    id: reproduce
    attributes:
      label: Steps to Reproduce
      description: A list of steps required to reproduce the bug.
      placeholder: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: A clear and concise description of what you expected to happen.
    validations:
      required: true

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: If applicable, paste screenshots into the markdown editor below to help explain the bug.
    validations:
      required: false

  - type: textarea
    id: device-information
    attributes:
      label: Device Information
      description: Please complete the following information.
      value: |
        | Question | Answer |
        | --- | --- |
        | Form Factor | [Smartphone or Desktop] |
        | Device | [e.g. iPhone 14, Surface Duo 3] |
        | OS | [e.g. Windows 11, iOS 16, Android 13] |
        | Browser | [e.g. Edge, Chrome, Safari] |
        | Version | [e.g. 102.0.1245.41] |
    validations:
      required: true

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: If nessesary, describe any other context about the problem.
    validations:
      required: false
      
