name: "Bug Report 🐛"
description: Something is wrong with the docs.microsoft.com site.
labels: ["bug"]

body:
  - type: markdown
    attributes:
      value: |
        Please make sure to [search for existing issues](https://github.com/microsoft/terminal/issues) before opening a new one!

        If this is a product issue, please contact the particular product's support instead of opening an issue here. For a list of support websites, see [Support for Microsoft products and apps](https://support.microsoft.com/all-products).

  - type: textarea
    id: description
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is.
    validations:
      required: true

  - type: textarea
    id: reproduce
    attributes:
      label: To Reproduce
      description: Steps to reproduce the behavior.
      placeholder: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      description: A clear and concise description of what you expected to happen.
    validations:
      required: true

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: If applicable, add screenshots to help explain your problem.
    validations:
      required: false
      
  - type: dropdown
    id: form-factor
    attributes:
      label: Form Factor
      description: What type of device did this bug occur on?
      options:
        - Desktop
        - Smartphone

  - type: input
    id: operating-system
    attributes:
      label: OS
      description: What operating system did this bug occur on?
      placeholder: Windows 11, iOS, android

  - type: markdown
    attributes:
      value: |
        Thanks for opening a bug report for the Microsoft Docs site. If you have entered an appropriate title and filled out the required information, select **Submit new issue**.
